### ISSUE TITLE
CSRF Verification failed

### ISSUE THREAD

**Issue by Iconnect-petale** [gnosis/safe-infrastructure#21]
Hello,
Got some issue trying to use the safe infrastructure

- Step 0 require step 1 for first function cause .env is not configured 

- At step 2 after executing `docker exec safe-infrastructure_cfg-web_1 python src/manage.py createsuperuser --noinput`
and trying to reach  http://localhost:8000/cfg/admin/
Got CRSF problem as image follow : 
![image](https://user-images.githubusercontent.com/92367487/152549516-f0d761f2-16c6-4ce0-8325-22a2375358a3.png)

I have tried to add localhost:8000 & 127.0.0.1 in settings.py of django in the image but i still got the issue.
Do you got some ideas on how to fix it ? 

- Step 2 `docker exec safe-infrastructure_txs-web_1 python manage.py createsuperuser --noinput`

Isn't working for me :  `CommandError: You must use --username with --noinput.`
But a user root as been created with previous command.

Regards

**Comment by Dewald928** [comment]
Any updates on this?

**Comment by jpalvarezl** [comment]
Thanks for reporting :) 
This commit https://github.com/gnosis/safe-infrastructure/commit/16cee7cc9215f28ccaa651fe2dbe9c9575fbdb25 fixed these issues. If you pull the latest changes, things should work.
I will close this issue for now, but if you are still experiencing problems, feel free to re-open this or create a new if it's about something else.

**Comment by Dewald928** [comment]
Thanks for the changes! I'm now able to add the chain info.

Just stuck at the transaction service part. 
Not too sure what I should make the transaction service uri as shown in the picture.
![image](https://user-images.githubusercontent.com/14140515/160384855-743d1dde-f12d-4e15-98bb-ff8ea420e760.png)

http://localhost:8000/cfg/api/v1/chains shows the chain info. But when the UI searches for http://localhost:8000/cfg/v1/chains (without the 'api' part, it doesn't receive anything), which I suspect has to do with the aforementioned fields?

Any assistance in this regard would be awesome, thanks.
