### ISSUE TITLE
Guide for production deployment

### ISSUE THREAD

**Issue by Janmajayamall** [gnosis/safe-infrastructure#22]
I think this repository is quite useful when deploying safe-infrastructure on a new chain. But when deploying in production (like on AWS for some other cloud provider) there are issues I faced, which I could have avoided incase a guide for production was provided. 

Few issues are as follows - 
1. Accessing CFG admin panel isn't by default allowed without OTP. I think few people would want this, but a small mention of this will be helpful. 
2. Loading chain.json in safe-infrastructure_cfg-web_1 throws error, even when loading is successful an chain info shows using API. I was quite confused when this happened for the first time. 
3. UI served on port 8080, queries cgw on localhost:8000 by default. In production, on client side, this will throw error. This can be fixed by pointing REACT_APP_GATEWAY_URL env variable to server instance. Just a small mention of the change for production will be helpful. 
4. UI build produced by yarn build (I am running safe-react on different server) does not have proper routing. I think in this case, it's quite possible that I am unable to configure the build properly. But a proper way to deploy safe-react in production will be helpful.

Again these issues are quite small but resolving them will help developers, that are unaware of safe architecture, deploy in-production faster.

**Comment by jpalvarezl** [comment]
Thanks for all the feedback! I am re-structuring the documentation to have a clearer guide as well as one can locally run or have a production setup of the services, in which I will incorporate your comments.
